name: onboarding
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_svg: ^2.0.7
  concentric_transition: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lottie: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/